#!/usr/bin/env python3
"""
gen_opts.py — Convert a grains.env shell file to a PETSc .opts file.

Usage:
    python3 scripts/gen_opts.py /path/to/grains.env > /path/to/grains.opts

The mapping from grains.env variable names to PETSc option flags:
    Nx  -> -Nx        Ny  -> -Ny        Nz  -> -Nz
    Lx  -> -Lx        Ly  -> -Ly        Lz  -> -Lz
    eps -> -eps       dim -> -dim

Unrecognised variables are silently skipped.
"""
import sys
import re

MAPPING = {
    "Nx":  "-Nx",
    "Ny":  "-Ny",
    "Nz":  "-Nz",
    "Lx":  "-Lx",
    "Ly":  "-Ly",
    "Lz":  "-Lz",
    "eps": "-eps",
    "dim": "-dim",
}


def main():
    if len(sys.argv) < 2:
        print("Usage: gen_opts.py <grains.env>", file=sys.stderr)
        sys.exit(1)

    env_file = sys.argv[1]
    print("# Auto-generated by gen_opts.py from", env_file)
    print("# Edit as needed, then run:")
    print("#   ./effective_k_ice_homog -options_file grains.opts ...")
    print()

    with open(env_file) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = re.match(r'^(\w+)\s*=\s*(.+)', line)
            if m:
                key, val = m.group(1), m.group(2).strip().strip('"').strip("'")
                if key in MAPPING:
                    print(f"{MAPPING[key]}  {val}")


if __name__ == "__main__":
    main()
