#!/usr/bin/env python3
"""
generate_study_opts.py — build the geometry and experiment .opts matrix for the
snow-thermal k_eff study.

The study varies porosity (5 values) x seed (5 realizations) x temperature
(8 values). Grain positions are temperature-independent, so the 25 packings are
generated once and reused at every temperature; what changes with temperature is
the discretisation and the kinetics.

WHY EVERY TEMPERATURE NEEDS ITS OWN FILES
-----------------------------------------
The solver rescales beta_sub0 and d0_sub0 by rho_vs(T_run)/rho_ice at runtime,
but beta_HK's own 1/sqrt(T) and d0's own 1/T are baked into the numbers written
in the .opts. Running -temp -35 against a beta_sub0 computed at -20 C therefore
updates the density ratio but NOT the intrinsic temperature dependence. eps and
the mesh are likewise temperature-specific. Hence one experiment file per
temperature and one geometry file per (packing, temperature).

WHY v_n IS DERIVED, NOT FIXED
-----------------------------
K&P Eq. 45 bounds eps by d0/(beta_sub*v_n). beta_sub grows like 1/rho_vs, which
falls steeply as temperature drops, so a FIXED v_n makes the bound collapse at
cold temperatures: at -40 C with v_n = 1e-9 m/s it demands eps = 0.11 um, i.e.
Nx = 25438 and 1.9e9 DOF -- about 39000 cores for a single 2 mm run, versus 105
at -5 C. That is an artifact: colder means slower, so v_n should fall too.

comp_eps.py's --vn_feature sets v_n = d0/(beta_sub*R_feat) self-consistently,
which makes the Eq. 45 bound equal R_feat exactly and temperature-independent.
R_feat is the smallest curvature feature the mesh must resolve -- for a
sintering packing that is the neck rim radius. With R_feat = 5 um the heat
bound takes over and eps lands at 2.14-2.30 um across the whole range, ~100
cores per run.

R_feat is the dominant cost knob and also controls how much of the pore network
the diffuse interface seals (band ~ 6*eps), so it is a required argument rather
than a default: pick it from the throat statistics of the packings in use.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from comp_eps import (                                    # noqa: E402
    compute_eps, rho_vs_sat, beta_HK, capillary_length, _RHO_ICE,
)


def derived_vn(T_C: float, alpha_c: float, R_feat: float) -> float:
    """v_n = d0 / (beta_sub * R_feat) -- see module docstring."""
    rho_rat = rho_vs_sat(T_C) / _RHO_ICE
    beta_uns = beta_HK(T_C, alpha_c) / rho_rat
    return capillary_length(T_C) / (beta_uns * R_feat)


def write_experiment(path: Path, T_C: float, p: dict, args) -> None:
    path.write_text(f"""\
# Experiment: T = {T_C:g} C   (generated by preprocess/generate_study_opts.py)
#
# Kinetics are temperature-specific. The solver rescales both of these by
# rho_vs(T)/rho_ice at runtime, but beta_HK's 1/sqrt(T) and d0's 1/T are baked
# in here -- do NOT reuse this file at another temperature.
#
#   alpha_c   = {args.alpha_c:.4e}   (condensation coefficient; the one free parameter)
#   rho_vs    = {p['rho_vs']:.4e} kg/m^3
#   rho_vs/rho_ice = {p['rho_rat']:.4e}

-temp {T_C:g}
-humidity {args.humidity:g}
-t_final {args.t_final:g}                  # {args.t_final/86400:g} days

-beta_sub0 {p['beta_uns']:.6e}       # K&P beta0 = beta_HK/(rho_vs/rho_i), UNSCALED
-d0_sub0 {p['d0']:.6e}         # physical gamma*V_m/(R*T), K&P Eq. 13 (NOT pre-scaled)

# Interface-CFL limiter: cap dt so no Gauss point moves more than dphimax per step
-dtCFL 1
-dtCFL_dphimax 0.2
-dtmax {args.dtmax:g}
""")


def write_geometry(path: Path, T_C: float, p: dict, pack: dict, args) -> None:
    path.write_text(f"""\
# Geometry: {pack['name']} at T = {T_C:g} C
# (generated by preprocess/generate_study_opts.py)
#
# Packing is temperature-independent; eps and the mesh are not. eps is sized by
# comp_eps.py with v_n derived self-consistently from R_feat = {args.R_feat*1e6:g} um,
# so the K&P Eq. 45 kinetic bound equals R_feat and does not collapse at cold
# temperatures. Binding bound here: {p['binding']}.
#
#   porosity (achieved) = {pack['porosity_achieved']:.4f}   target {pack['porosity_target']:.4f}
#   grains              = {pack['n_grains']}
#   contact gap         = {pack['contact_gap_m']*1e6:.2f} um
#   coordination number = {pack['coordination_number']:.2f}
#   diffuse band 6*eps  = {6*p['eps']*1e6:.2f} um   (compare with the throat sizes above)

-ic_type multi_grains_file
-grains_file {pack['grains_file']}
-ic_grain_union 1                 # phi=0.5 contour sits on the sharp geometry for any eps

-dim 2
-Lx {pack['Lx']:.6e}
-Ly {pack['Ly']:.6e}
-Nx {p['Nx']}                          # ceil(sqrt(2)*Lx/eps)
-Ny {p['Ny']}

-eps {p['eps']:.6e}              # comp_eps.py @ T={T_C:g}C, safety={args.safety:g}
-eps_valid_temp {T_C:g}                # solver ABORTS if -temp differs by >1C

-delt_t {args.delt_t:g}
""")


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Generate the geometry x experiment .opts matrix.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument("--packings-dir", required=True, type=Path,
                    help="directory of packing subdirs (each with grains.dat + metadata.json)")
    ap.add_argument("--out-dir", required=True, type=Path,
                    help="inputs/ root; geometry/ and experiment/ are created under it")
    ap.add_argument("--temps", type=float, nargs="+",
                    default=[-5, -10, -15, -20, -25, -30, -35, -40])
    ap.add_argument("--R-feat", type=float, required=True,
                    help="smallest curvature feature to resolve [m]; sets v_n "
                         "self-consistently and dominates cost (see docstring)")
    ap.add_argument("--alpha-c", type=float, default=1.341e-2,
                    help="condensation coefficient; 1.341e-2 reproduces the "
                         "committed -20 C kinetics (beta_sub0 = 5.9216e5)")
    ap.add_argument("--safety", type=float, default=0.5)
    ap.add_argument("--Rave", type=float, default=45e-6,
                    help="mean grain radius, for the geometric eps bound")
    ap.add_argument("--humidity", type=float, default=1.00)
    ap.add_argument("--t-final", type=float, default=28 * 86400.0)
    ap.add_argument("--delt-t", type=float, default=1.0e-4)
    ap.add_argument("--dtmax", type=float, default=2.0e2)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    packs = []
    for d in sorted(args.packings_dir.iterdir()):
        meta = d / "metadata.json"
        dat = d / "grains.dat"
        if not (meta.is_file() and dat.is_file()):
            continue
        m = json.loads(meta.read_text())
        if m.get("problems"):
            print(f"  SKIP {d.name}: {m['problems'][0][:70]}", file=sys.stderr)
            continue
        m["name"] = d.name
        # Project-root-relative, NOT absolute: these .opts are committed and
        # read on the cluster too, where the checkout lives somewhere else.
        # Both scripts/Studio/run_enceladus.sh and scripts/HPC/run_enceladus.sh
        # cd to PROJECT_ROOT before launching, so this resolves on any machine.
        try:
            m["grains_file"] = str(dat.resolve().relative_to(PROJECT_ROOT))
        except ValueError:
            m["grains_file"] = str(dat.resolve())
            print(f"  NOTE {d.name}: packing lives outside the project root, "
                  f"writing an absolute -grains_file (not portable)", file=sys.stderr)
        packs.append(m)

    if not packs:
        print("No usable packings found.", file=sys.stderr)
        return 1

    geo_dir = args.out_dir / "geometry"
    exp_dir = args.out_dir / "experiment"
    if not args.dry_run:
        geo_dir.mkdir(parents=True, exist_ok=True)
        exp_dir.mkdir(parents=True, exist_ok=True)

    total_cores = 0
    print(f"{'T[C]':>5} {'eps[um]':>9} {'Nx':>6} {'band[um]':>9} "
          f"{'DOF/run':>12} {'cores':>7} {'binding':>10}")
    for T in args.temps:
        vn = derived_vn(T, args.alpha_c, args.R_feat)
        # eps/mesh depend on the domain, which is the same for every packing.
        p0 = compute_eps(Lx=packs[0]["Lx"], Ly=packs[0]["Ly"], T0_C=T,
                         alpha_c=args.alpha_c, Rave=args.Rave,
                         safety=args.safety, v_n=vn)
        dof = 3 * p0["Nx"] * p0["Ny"]
        cores = math.ceil(dof / 50000)
        total_cores += cores * len(packs)
        print(f"{T:>5g} {p0['eps']*1e6:>9.4f} {p0['Nx']:>6} {6*p0['eps']*1e6:>9.2f} "
              f"{dof:>12,} {cores:>7} {p0['binding']:>10}")

        if args.dry_run:
            continue

        write_experiment(exp_dir / f"snow_T{T:g}.opts", T, p0, args)
        for pk in packs:
            p = compute_eps(Lx=pk["Lx"], Ly=pk["Ly"], T0_C=T,
                            alpha_c=args.alpha_c, Rave=args.Rave,
                            safety=args.safety, v_n=vn)
            write_geometry(geo_dir / f"{pk['name']}_T{T:g}.opts", T, p, pk, args)

    n = len(packs) * len(args.temps)
    print(f"\n  {len(packs)} packings x {len(args.temps)} temperatures = {n} runs")
    print(f"  {total_cores} core-allocations total "
          f"({total_cores/len(args.temps)/len(packs):.0f} per run average)")
    if args.dry_run:
        print("  (dry run: no files written)")
    else:
        print(f"  geometry -> {geo_dir}")
        print(f"  experiment -> {exp_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
